=== JonasReich/OpenUnrealAutomationTools/python/openunrealautomation/resources/openunreal_logparse_patterns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="StyleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Literal" />
            <xs:enumeration value="Regex" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PatternType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="Style" type="StyleType" default="Literal" use="optional" />
                <xs:attribute name="StringVariables" type="TagOrVarListType" use="optional" />
                <xs:attribute name="NumericVariables" type="TagOrVarListType" use="optional" />
                <xs:attribute name="SuccessFlags" type="TagOrVarListType" use="optional" />
                <xs:attribute name="FailureFlags" type="TagOrVarListType" use="optional" />
                <xs:attribute name="Tags" type="TagOrVarListType" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Use for list of named tags or variables -->
    <xs:simpleType name="TagOrVarListType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[\w_]+(;[\w_]+)*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SeverityType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Warning" />
            <xs:enumeration value="Severe_Warning" />
            <xs:enumeration value="Error" />
            <xs:enumeration value="Message" />
            <xs:enumeration value="Fatal" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PatternListType">
        <xs:sequence>
            <xs:choice>
                <xs:element name="Include" type="PatternType" />
                <xs:element name="Exclude" type="PatternType" />
            </xs:choice>
            <xs:element name="Include" type="PatternType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Exclude" type="PatternType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="Name" type="xs:string" use="required" />
        <xs:attribute name="Severity" type="SeverityType" use="required" />
        <xs:attribute name="Tags" type="TagOrVarListType" use="optional" />
        <xs:attribute name="Hidden" type="xs:boolean" default="false" use="optional" />
        <xs:attribute name="SuccessFlags" type="TagOrVarListType" use="optional" />
        <xs:attribute name="FailureFlags" type="TagOrVarListType" use="optional" />
    </xs:complexType>

    <xs:complexType name="TemplateType">
        <xs:sequence>
            <!-- First patterns, then scopes, then links (that's the order they are parsed) -->
            <xs:choice>
                <xs:element name="Patterns" type="PatternListType" />
                <xs:element name="Scope" type="ScopeType" />
                <xs:element name="Link" type="LinkType" />
            </xs:choice>
            <xs:element name="Patterns" type="PatternListType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Scope" type="ScopeType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Link" type="LinkType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="Name" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:complexType name="LinkType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="Template" type="xs:IDREF" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="ScopeType">
        <xs:sequence>
            <xs:element name="Start" type="PatternType" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="End" type="PatternType" minOccurs="1" maxOccurs="unbounded" />

            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Scope" type="ScopeType" />
                <xs:element name="Link" type="LinkType" />
                <xs:element name="Patterns" type="PatternListType" />
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="Name" type="xs:string" use="required" />
        <!-- Exit scope if a line does not match. Useful if you don't have a specific scope exit
        point. -->
        <xs:attribute name="RequireAllLinesMatch" type="xs:boolean" use="optional" />
        <xs:attribute name="DisplayNameVariable" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="TargetType">
        <xs:sequence>
            <xs:element name="Scope" type="ScopeType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Patterns" type="PatternListType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Link" type="LinkType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="Name" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:element name="Root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Template" type="TemplateType" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="Target" type="TargetType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JonasReich/OpenUnrealAutomationTools/python/openunrealautomation/resources/logparse_patterns.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
    XML Escape characters:
    "   &quot;
    '   &apos;
    <   &lt;
    >   &gt;
    &   &amp;
-->
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="openunreal_logparse_patterns.xsd">

    <Template Name="TeamCity">
        <!-- Include this first to prevent a line from this to e.g. cause a UAT stack frame that
        contains the entire log file -->
        <Scope Name="TC Start Boilerplate">
            <Start Style="Regex">Build '.*' .+, branch '.+'</Start>
            <End Style="Literal">TeamCity server version is</End>
            <Patterns Name="TopFileErrorSummary" Severity="Error">
                <Include Style="Regex">Finished .* with status FAILURE</Include>
            </Patterns>
        </Scope>
        <Patterns Name="TCMessages" Severity="Message">
            <Include Style="Literal">]E:		 </Include>
            <Include Style="Literal">]i:		 </Include>
        </Patterns>
    </Template>

    <Template Name="ExitCodes">
        <Patterns Name="Exit Codes" Severity="Message" Hidden="true">
            <Include Style="Regex" StringVariables="UAT_Command"
                NumericVariables="Duration;ExitCode">Took (?P&lt;Duration&gt;\d+,\d+)s to run (?P&lt;UAT_Command&gt;.+), ExitCode=(?P&lt;ExitCode&gt;\d+)</Include>
            <Include Style="Regex" StringVariables="ExitCode">subprocess.CalledProcessError: (?P&lt;Command&gt;.+) returned non-zero exit status (?P&lt;ExitCode&gt;-?\d+)</Include>
            <Include Style="Regex">(?P&lt;Command&gt;.+) exiting with ExitCode=(?P&lt;ExitCode&gt;-?\d+)</Include>
        </Patterns>
    </Template>

    <Template Name="Unreal">
        <!-- TODO: Add ensure summary to display name -->
        <!-- Unfortunately any such logs can easily leak if mirrored by TeamCity :( -->
        <!--
        <Scope Name="Exception Callstack">
            <Start>Error: begin: stack for UAT</Start>
            <End>Error: end: stack for UAT</End>
            <Patterns Name="Callstack" Tags="Code" Severity="Error">
                <Include Style="Regex">.*</Include>
            </Patterns>
        </Scope>
        -->

        <Patterns Name="CookParams" Severity="Message">
            <Include Style="Regex" StringVariables="CookCultures">LogCookCommandlet: Display:\s+CookCultures: \((?P&lt;CookCultures&gt;.+)\)</Include>
            <Include Style="Regex" StringVariables="IniMapSections">LogCookCommandlet: Display:\s+IniMapSections: \((?P&lt;IniMapSections&gt;.+)\)</Include>
        </Patterns>

        <Patterns Name="Command Line" Severity="Message">
            <Include>LogInit: Command Line:</Include>
        </Patterns>

        <Patterns Name="Exit Status" Severity="Message">
            <Include SuccessFlags="auto">LogExit: Exiting.</Include>
        </Patterns>

        <Patterns Name="Suppressed Messages" Severity="Message" Hidden="true">
            <!-- duplicate messages from map check message log -->
            <Include>is not valid. See the MapCheck log messages for details</Include>
            <!-- any non-error / non-warning log lines. this allone can speed up parsing times
            significantly. From 43 to 34 seconds for 30k log lines -->
            <Include>: Display: </Include>
        </Patterns>

        <Patterns Name="Load Issues: One File Per Actor" Tags="Code" Severity="Error">
            <Include Style="Regex">LoadErrors: Error: .* Failed import for</Include>
        </Patterns>

        <Patterns Name="Load Issues: One File Per Actor" Tags="Code" Severity="Severe_Warning">
            <Include Style="Literal">LogEngine: Warning: Can't find actor</Include>
            <Include Style="Regex">LogEngine: Warning: Failed to load .* from loaded package /Game/__ExternalActors__</Include>
        </Patterns>

        <Patterns Name="Load Errors + Warnings" Tags="Code" Severity="Error">
            <Include Style="Regex">Failed to load '.*': Can't find file</Include>
            <Include Style="Literal">LogLinker: Warning: Unable to load</Include>
            <Include Style="Literal">LogLinker: Warning: VerifyImport: Failed to load</Include>
            <Include Style="Literal">Failed to load package for import object</Include>
            <Include Style="Literal">LogLinker: Display: CreateExport: Failed to load Parent for ScriptStruct</Include>
        </Patterns>

        <Patterns Name="Developer Asset References" Severity="Warning">
            <Include Style="Regex" StringVariables="Developer">imported Serialize:\/Game\/Developers\/(?P&lt;Developer&gt;.*?)\/</Include>
        </Patterns>

        <Patterns Name="Missing Cook Packages (JsonFiles)" Tags="Code" Severity="Warning">
            <Include Style="Regex">Unable to find package for cooking /JsonData/.* Instigator</Include>
        </Patterns>

        <Patterns Name="Missing Cook Packages (other)" Severity="Warning">
            <Include Style="Regex">Unable to find package for cooking</Include>
        </Patterns>

        <Patterns Name="Export Warnings" Severity="Warning">
            <Include>but it was never saved as an export</Include>
        </Patterns>

        <Patterns Name="Blueprint Errors" Tags="Code" Severity="Error">
            <Include>LogBlueprint: Error:</Include>
            <Include>Error compiling pin</Include>
            <Include Style="Regex">Error:.*\[AssetLog\] .* \[Compiler\]</Include>
        </Patterns>

        <Patterns Name="Blueprint Warnings" Tags="Code;Content" Severity="Warning">
            <Include Style="Regex">Warning:.*\[AssetLog\] .* \[Compiler\]</Include>
        </Patterns>

        <Patterns Name="Invalid Gameplay Tags" Tags="Content" Severity="Severe_Warning">
            <Include Style="Regex" StringVariables="GameplayTag">Invalid GameplayTag (?P&lt;GameplayTag&gt;.*) found in property</Include>
            <Include Style="Regex" StringVariables="GameplayTag">Invalid GameplayTag (?P&lt;GameplayTag&gt;.*) found in object</Include>
        </Patterns>

        <Patterns Name="Material Errors" Tags="Art;Code" Severity="Error">
            <Include Style="Literal">Failed to compile Material</Include>
            <Include Style="Literal">LogMaterial: Error</Include>
            <Include Style="Regex">.ush(.*):  err0r</Include>
        </Patterns>
        <Patterns Name="Material Warnings" Tags="Art" Severity="Warning">
            <Include Style="Literal">LogMaterial: Warning</Include>
        </Patterns>
        <Patterns Name="Skeleton Issues" Tags="Art" Severity="Warning">
            <Include Style="Regex">LogScript: Warning: Script Msg:.*Unable to (find|retrieve) bone index</Include>
        </Patterns>

        <Patterns Name="Collision Issues" Tags="Art" Severity="Warning">
            <Include Style="Regex">LogPhysics: Warning: Scale for .* has a component set to zero</Include>
        </Patterns>

        <!-- Generic issues -->
        <Patterns Name="Errors" Tags="Code" Severity="Error">
            <Include>Error:</Include>
        </Patterns>
        <Patterns Name="Warnings" Tags="Code" Severity="Warning">
            <Include>Warning:</Include>
        </Patterns>

        <Scope Name="DDC Resource Stats" RequireAllLinesMatch="true">
            <Start Style="Literal">LogCook: Display: DDC Resource Stats</Start>
            <End Style="Literal"></End>
            <Patterns Name="DDC Stats" Tags="Code" Severity="Message" Hidden="true">
                <Include Style="Literal">LogCook: Display: DDC Resource Stats</Include>
                <Include Style="Literal">LogCook: Display: ==========</Include>
                <Include Style="Literal">LogCook: Display: Asset Type</Include>
                <Include Style="Literal">LogCook: Display: ----------</Include>
                <Include Style="Regex" StringVariables="DDC_Key"
                    NumericVariables="DDC_TotalTime;DDC_GameThreadTime;DDC_AssetNum;DDC_MB">LogCook: Display: (?P&lt;DDC_Key&gt;.+?)\s+(?P&lt;DDC_TotalTime&gt;[+-]?[0-9]*[.]?[0-9]+)\s+(?P&lt;DDC_GameThreadTime&gt;[+-]?[0-9]*[.]?[0-9]+)\s+(?P&lt;DDC_AssetNum&gt;[+-]?[0-9]*[.]?[0-9]+)\s+(?P&lt;DDC_MB&gt;[+-]?[0-9]*[.]?[0-9]+)</Include>
            </Patterns>
        </Scope>

        <Scope Name="Warning/Error Summary">
            <Start Style="Literal">LogInit: Display: Warning/Error Summary (Unique only)</Start>
            <End Style="Regex">LogInit: Display: Success - \d+ error\(s\), \d+ warning\(s\)</End>
            <End Style="Regex">LogInit: Display: Failure - \d+ error\(s\), \d+ warning\(s\)</End>
            <Patterns Name="Warning/Error Summary (Success)" Severity="Warning" SuccessFlags="auto">
                <Include Style="Regex">LogInit: Display: Success - \d+ error\(s\), \d+ warning\(s\)</Include>
            </Patterns>
            <Patterns Name="Warning/Error Summary (Failure)" Severity="Error" FailureFlags="auto">
                <Include Style="Regex">LogInit: Display: Failure - \d+ error\(s\), \d+ warning\(s\)</Include>
            </Patterns>
            <Patterns Name="Duplicate Issues (Ignore)" Severity="Message" Hidden="true">
                <Include Style="Regex">.*</Include>
            </Patterns>
        </Scope>
    </Template>

    <Template Name="UAT">
        <Patterns Name="UAT Errors" Severity="Error">
            <Include Style="Literal">ERROR: </Include>
            <Include Style="Literal">Missing files required to build</Include>
        </Patterns>
        <Patterns Name="UAT Warnings" Severity="Warning">
            <Include Style="Literal">WARNING: </Include>
        </Patterns>
        <Patterns Name="UAT Runner Command Lines" Severity="Message" Hidden="true">
            <Include Style="Regex">Running: .*</Include>
        </Patterns>
        <Link Template="ExitCodes" />
    </Template>

    <Template Name="MSVC">
        <Patterns Name="MSVC Compile Errors" Severity="Error" Tags="Code" FailureFlags="auto">
